server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /teams-wechat-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.28.128:3306/teams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
  redis:
    database: 0
    host: 192.168.28.128
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: 192.168.28.128
      port: 27017
      database: teams
      authentication-database: admin
      username: admin
      password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gec.teams.wechat.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
      level:
        root: info
        com.gec.teams.db.mapper: warn
      pattern:
        console: "%d{HH:mm:ss}  %-5level  %msg%n"
teams:
  jwt:
    secret: 123456
    expire: 5 #令牌过期时间
    cache-expire: 10 #令牌保存时间
wx:
  app-id: 
  app-secret: 
